# referer host
verification: "127.0.0.1"
# MeiliSearch 密码至少16字节
meiliSearch:
  host: "0.0.0.0"
  apiKey: "yourApikey"
  port: 7700
# redis
redis:
  host: "0.0.0.0"
  password: "yourPass"
  port: 6379
  db: 1
# rabbitmq
rabbitmq:
  host: "0.0.0.0"
  username: "yourUsername"
  password: "yourPass"
  port: 5672
# email smtp 163
emailSmtp:
  smtp: "smtp.163.com"
  email: "yourEmail"
  password: "your SMTP key"
  port: 465
# database postgres
database:
  driverName: "postgres"
  host: "0.0.0.0"
  username: "postgres"
  password: "yourPass"
  port: 5432
  baseName: "benetnasch"
# oss
oss:
  endPoint: "yourOss"
  accessKeyID: ""
  accessKeySecret: ""
  bucketName: ""