# referer host
verification: "your domain name"
# MeiliSearch 密码至少16字节
meiliSearch:
  host: "172.17.0.1"
  apiKey: "yourApikey"
  port: 7700
# redis
redis:
  host: "172.17.0.1"
  password: "yourPass"
  port: 6379
  db: 1
# rabbitmq
rabbitmq:
  host: "172.17.0.1"
  username: "yourUsername"
  password: "yourPass"
  port: 5672
# email smtp
emailSmtp:
  smtp: "smtp.163.com"
  email: "yourEmail"
  password: "your SMTP key"
  port: 465
# database postgres
database:
  driverName: "postgres"
  host: "172.17.0.1"
  username: "postgres"
  password: "yourPass"
  port: 5432
  baseName: "benetnasch"
# oss
oss:
  endPoint: "yourOss"
  accessKeyID: ""
  accessKeySecret: ""
  bucketName: ""