version: '3'
services:
  benetnasch:
    image: benetnasch:latest
    container_name: benetnasch
    ports:
      - '7777:7777'
    volumes:
      - /usr/data/app/resource/:/app/resource
    environment:
      - TZ=Asia/Shanghai
    restart: always
  postgresql:
    image: postgres:latest
    container_name: PG
    ports:
      - '5432:5432'
    volumes:
      - /usr/data/pgsql/data:/var/lib/postgresql/data
    environment:
      - TZ=Asia/Shanghai
      - PGDATA=/var/lib/postgresql/data
      - LANG=C.UTF-8
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=yourPass
    restart: always
  nginx:
    image: nginx:stable
    container_name: nginx
    ports:
      - '80:80'
      - '10001:8008'
    volumes:
      - /usr/data/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - /usr/data/nginx/vue:/usr/local/vue
    environment:
      - TZ=Asia/Shanghai
    restart: always
  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --requirepass yourPass && sysctl vm.overcommit_memory=1
    ports:
      - '6379:6379'
    volumes:
      - /usr/data/redis/data:/data
    environment:
      - TZ=Asia/Shanghai
    restart: always
  meiliSearch:
    image: getmeili/meilisearch:v1.1
    container_name: meili
    ports:
      - '7700:7700'
    volumes:
      - /usr/data/meilisearch/data:/meili_data
    environment:
      - MEILI_NO_ANALYTICS=true
      - TZ=Asia/Shanghai
      - MEILI_MASTER_KEY=yourApikey
      - MEILI_ENV=production
    restart: always
  rabbitmq:
    image: rabbitmq:3.11.13-management-alpine
    container_name: rabbit
    ports:
      - '5672:5672'
      - '15672:15672'
    volumes:
      - /usr/data/rabbit:/var/lib/rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=yourUsername
      - RABBITMQ_DEFAULT_PASS=yourPass